spring:
  application:
    name: elec
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 10MB

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
  type-enums-package: com.cjr.elec